apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-app
spec:
  selector:
    matchLabels:
      app: course-service-app
  template:
    metadata:
      labels:
        app: course-service-app
    spec:
      containers:
        - name: course-service-app
          image: 637223683609.dkr.ecr.us-east-1.amazonaws.com/lms-microservices-course-service-linux:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087


          env:
            - name: ENABLE_EUREKA
              valueFrom:
                configMapKeyRef:
                  name: enable-eureka
                  key: enable_eureka_value

            - name: CONFIG_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: config_server_url
                  name: config-server-cm


#            - name: EUREKA_SERVER_ADDRESS
#              valueFrom:
#                configMapKeyRef:
#                  key: eureka_service_address
#                  name: eureka-cm

---

apiVersion: v1
kind: Service
metadata:
  name: course-service-svc
spec:
  type: LoadBalancer
  selector:
    app: course-service-app
  ports:
    - port: 80
      targetPort: 8087

