server:
  port: 8087

spring:
  application:
    name: COURSE-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
  data:
    mongodb:
      uri: mongodb+srv://drsevere:Pinpad_67@lms-cluster.51t9vbr.mongodb.net/lms-cluster
      database: lms-cluster

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

eureka:
  client:
    enabled: ${ENABLE_EUREKA:true}

